[package]
name = "duallnet"
version = "1.0.0"
authors = ["silvioprog <silvioprog@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
libc = "0.2.66"
serde_plain = "0.3.0"
dns-lookup = "1.0.1"